"""Subclass of dialog_base, which is generated by wxFormBuilder."""
import os
import re

import wx

from . import dialog_base

class Dialog(dialog_base.KiBuzzardDialog):
    def __init__(self, parent, last_str, kicad_ver, func):
        dialog_base.KiBuzzardDialog.__init__(self, parent)

        best_size = self.BestSize
        # hack for some gtk themes that incorrectly calculate best size
        best_size.IncBy(dx=0, dy=30)
        self.SetClientSize(best_size)
        self.m_textCtrl4.SetValue(last_str)
        self.func = func
        self.kicad_ver = kicad_ver

    def OnTextEnter(self, event):
        self.func(self.m_textCtrl4.GetValue(), self.kicad_ver)
        #self.EndModal(wx.ID_OK)

    def GetValue(self):
        return self.m_textCtrl4.GetValue()
        
